language: node_js
node_js:
  - "6"
express:
  - "4"

addons:
  ssh_known_hosts: fansdev.warungtegal.id
before_deploy:
 - openssl aes-256-cbc -K deploy_rsa.enc -iv deploy_rsa.enc -in deploy_rsa.enc -out /tmp/deploy_rsa -d
 - eval "$(ssh-agent -s)"
 - chmod 600 /tmp/deploy_rsa
 - ssh-add /tmp/deploy_rsa

deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet /home/fans17/trytravis fans17@fansdev.warungtegal.id:/home/fans17/trytravis -p 3010
  on:
    branch: master
